name: Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install gpr tool
      # Helper tool from Jamie Cansdale (GitHub Support) Thx!!!
      run: dotnet tool install --tool-path tools gpr
    - name: Build with Cake Action
      env:
        azure-key-vault-url: ${{ secrets.AZURE_KEY_VAULT_URL }}
        azure-key-vault-client-id: ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }}
        azure-key-vault-client-secret: ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }}
        azure-key-vault-certificate: ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }}
      uses: ecampidoglio/cake-action@v1
      with:
        cake-version: 0.38.5
        cake-bootstrap: true
        target: appveyor
    - name: Publish NuGet
      if: success()
      #run: dotnet nuget push Publish\*.nupkg --source https://nuget.pkg.github.com/punker76/MahApps.Metro.SimpleChildWindow/index.json -k ${{ secrets.PACKAGE_ACCESS_TOKEN }}
      run: tools/gpr push Publish\*.nupkg -k ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: Publish/*.*
